apiVersion: batch/v1
kind: Job
metadata:
  name: standard-job
  namespace: windows-job
spec:
  template:
    metadata:
      labels:
        app: standard-job
        tier: backend
        track: stable
    spec:
      containers:
      - name: standard-job
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        command: 
        - powershell.exe
        - -command
        - " Start-Sleep -Seconds 180 "
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/os: windows

