apiVersion: apps/v1
kind: Deployment
metadata:
  name: standard-2022-deployment
spec:
  selector:
    matchLabels:
      app: standard-2022-deployment
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: standard-2022-deployment
        tier: backend
        track: stable
    spec:
      containers:
      - name: standard-2022-deployment
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        command: 
        - powershell.exe
        - -command
        - " ping -t google.com "
      nodeSelector:
        kubernetes.io/os: windows

