apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-limits
  namespace: limits
spec:
  selector:
    matchLabels:
      app: deployment-with-limits
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-with-limits
        tier: backend
        track: stable
    spec:
      containers:
      - name: deployment-with-limits
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2022
        command: 
        - powershell.exe
        - -command
        - " ping -t google.com "
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      nodeSelector:
        kubernetes.io/os: windows

