apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-pull-failed
  namespace: image-pull-failed
spec:
  selector:
    matchLabels:
      app: image-pull-failed
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: image-pull-failed
        tier: backend
        track: stable
    spec:
      containers:
      - name: image-pull-failed
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        command: 
        - powershell.exe
        - -command
        - " ping -t google.com "
      nodeSelector:
        kubernetes.io/os: windows

